-- FinGuard Core baseline schema.
--
-- 작성 방식: 엔티티 매핑에서 Hibernate 스키마 생성으로 초안을 뽑은 뒤 사람이 검토·수정했다
-- (docs/adr/0002-flyway-owns-core-api-schema.md). 런타임에는 Hibernate가 스키마를 만들지 않는다
-- — ddl-auto 는 validate 다.
--
-- 초안에서 손댄 곳:
--   1. 제약 이름을 결정적으로 바꿨다. 생성물은 FKateqfe8aojf4ni5mq4r03sb7t 같은 난수 이름이라
--      마이그레이션을 읽을 수도, 다음 생성물과 대조할 수도 없다.
--   2. 핵심 테이블 사이 FK를 추가했다. 생성물에는 컬렉션 테이블 FK만 있었다.
--      엔티티가 연관 대신 문자열 식별자를 들고 있어서 Hibernate가 알 수 없기 때문이다.
--   3. 조회 경로 인덱스를 추가했다.
--
-- 감사 테이블(audit_events, security_auth_events)에는 FK를 걸지 않는다. 감사 기록은 증거이므로
-- 참조 무결성 위반 때문에 기록 자체가 실패하는 상황을 만들지 않는다.

-- ---------------------------------------------------------------- 식별자 기준점

create table employees (
    employee_id varchar(64) not null,
    created_at  timestamp(6) with time zone not null,
    primary key (employee_id)
);

create table consumers (
    consumer_id varchar(64) not null,
    created_at  timestamp(6) with time zone not null,
    primary key (consumer_id)
);

-- ---------------------------------------------------------------- 권한 원천

create table permission_templates (
    template_id              varchar(64) not null,
    task_type                varchar(64) not null check (task_type in ('LOAN_REVIEW')),
    default_duration_minutes integer     not null,
    status                   varchar(32) not null check (status in ('ACTIVE', 'INACTIVE')),
    version                  bigint      not null,
    primary key (template_id)
);

create table permission_template_allowed_tools (
    template_id varchar(64) not null,
    tool        varchar(64) not null check (tool in ('CREDIT_SCORE_READ', 'INCOME_READ', 'DEBT_READ')),
    primary key (template_id, tool),
    constraint fk_template_tools_template foreign key (template_id) references permission_templates
);

create table permission_template_allowed_data (
    template_id varchar(64) not null,
    data_type   varchar(64) not null check (data_type in ('CREDIT_SCORE', 'INCOME', 'DEBT')),
    primary key (template_id, data_type),
    constraint fk_template_data_template foreign key (template_id) references permission_templates
);

-- 직원당 하나. Agent 권한의 상한선이다.
create table employee_authorities (
    employee_id            varchar(64) not null,
    status                 varchar(32) not null check (status in ('ACTIVE', 'INACTIVE')),
    allowed_customer_scope varchar(32) not null check (allowed_customer_scope in ('ALL')),
    version                bigint      not null,
    primary key (employee_id),
    constraint fk_employee_authority_employee foreign key (employee_id) references employees
);

create table employee_authority_allowed_tools (
    employee_id varchar(64) not null,
    tool        varchar(64) not null check (tool in ('CREDIT_SCORE_READ', 'INCOME_READ', 'DEBT_READ')),
    primary key (employee_id, tool),
    constraint fk_authority_tools_authority foreign key (employee_id) references employee_authorities
);

create table employee_authority_allowed_data (
    employee_id varchar(64) not null,
    data_type   varchar(64) not null check (data_type in ('CREDIT_SCORE', 'INCOME', 'DEBT')),
    primary key (employee_id, data_type),
    constraint fk_authority_data_authority foreign key (employee_id) references employee_authorities
);

-- (consumer_id, purpose)는 유일하다. 같은 조합이 둘이면 어느 쪽을 볼지 정할 수 없다.
create table consumer_mandates (
    mandate_id  bigint generated by default as identity,
    consumer_id varchar(64) not null,
    purpose     varchar(64) not null check (purpose in ('LOAN_REVIEW')),
    status      varchar(32) not null check (status in ('ACTIVE', 'REVOKED', 'EXPIRED')),
    version     bigint      not null,
    primary key (mandate_id),
    constraint uk_consumer_mandate_consumer_purpose unique (consumer_id, purpose),
    constraint fk_consumer_mandate_consumer foreign key (consumer_id) references consumers
);

create table consumer_mandate_allowed_data (
    mandate_id bigint      not null,
    data_type  varchar(64) not null check (data_type in ('CREDIT_SCORE', 'INCOME', 'DEBT')),
    primary key (mandate_id, data_type),
    constraint fk_mandate_data_mandate foreign key (mandate_id) references consumer_mandates
);

-- ---------------------------------------------------------------- 업무와 발급 권한

-- 이 Case의 consumer_id 가 Runtime Tool Call의 고객 Scope 기준이 된다.
create table financial_cases (
    case_id     varchar(64) not null,
    employee_id varchar(64) not null,
    consumer_id varchar(64) not null,
    task_type   varchar(64) not null check (task_type in ('LOAN_REVIEW')),
    template_id varchar(64) not null,
    status      varchar(32) not null check (status in ('ACTIVE', 'COMPLETED', 'EXPIRED', 'CANCELLED')),
    issued_at   timestamp(6) with time zone not null,
    expires_at  timestamp(6) with time zone not null,
    version     bigint      not null,
    primary key (case_id),
    constraint fk_case_employee foreign key (employee_id) references employees,
    constraint fk_case_consumer foreign key (consumer_id) references consumers,
    constraint fk_case_template foreign key (template_id) references permission_templates
);

-- source_version_* 이 현재 원본 버전과 하나라도 다르면 TASK_PASSPORT_STALE 이다.
create table task_passports (
    passport_id                        varchar(64) not null,
    agent_id                           varchar(64) not null,
    employee_id                        varchar(64) not null,
    case_id                            varchar(64) not null,
    consumer_id                        varchar(64) not null,
    task_type                          varchar(64) not null check (task_type in ('LOAN_REVIEW')),
    status                             varchar(32) not null check (status in ('ACTIVE', 'EXPIRED', 'REVOKED', 'STALE')),
    issued_at                          timestamp(6) with time zone not null,
    expires_at                         timestamp(6) with time zone not null,
    source_version_employee_authority  bigint not null,
    source_version_permission_template bigint not null,
    source_version_financial_case      bigint not null,
    source_version_consumer_mandate    bigint not null,
    primary key (passport_id),
    constraint fk_passport_employee foreign key (employee_id) references employees,
    constraint fk_passport_case foreign key (case_id) references financial_cases,
    constraint fk_passport_consumer foreign key (consumer_id) references consumers
);

create table task_passport_allowed_tools (
    passport_id varchar(64) not null,
    tool        varchar(64) not null check (tool in ('CREDIT_SCORE_READ', 'INCOME_READ', 'DEBT_READ')),
    primary key (passport_id, tool),
    constraint fk_passport_tools_passport foreign key (passport_id) references task_passports
);

create table task_passport_allowed_data (
    passport_id varchar(64) not null,
    data_type   varchar(64) not null check (data_type in ('CREDIT_SCORE', 'INCOME', 'DEBT')),
    primary key (passport_id, data_type),
    constraint fk_passport_data_passport foreign key (passport_id) references task_passports
);

-- ---------------------------------------------------------------- 실행과 입력

create table agent_runs (
    agent_run_id varchar(64) not null,
    agent_id     varchar(64) not null,
    employee_id  varchar(64) not null,
    case_id      varchar(64) not null,
    passport_id  varchar(64) not null,
    status       varchar(32) not null check (status in ('CREATED', 'RUNNING', 'COMPLETED', 'FAILED')),
    started_at   timestamp(6) with time zone not null,
    primary key (agent_run_id),
    constraint fk_agent_run_employee foreign key (employee_id) references employees,
    constraint fk_agent_run_case foreign key (case_id) references financial_cases,
    constraint fk_agent_run_passport foreign key (passport_id) references task_passports
);

create table agent_run_input_refs (
    agent_run_id    varchar(64) not null,
    input_ref_order integer     not null,
    input_ref       varchar(64) not null,
    primary key (agent_run_id, input_ref_order),
    constraint fk_run_input_refs_run foreign key (agent_run_id) references agent_runs
);

-- 원문은 저장하지 않는다. 식별자와 해시만 남는다 (docs/06 §24).
create table secured_agent_inputs (
    input_ref        varchar(64)  not null,
    agent_run_id     varchar(64)  not null,
    input_hash       varchar(128) not null,
    content_language varchar(16),
    registered_at    timestamp(6) with time zone not null,
    primary key (input_ref),
    constraint fk_secured_input_run foreign key (agent_run_id) references agent_runs
);

-- 같은 (input_hash, model_version)은 재평가하지 않는다 (docs/06 §24.2).
-- evaluation_status 가 "검사하지 않았음"과 "검사했고 음성"을 구분한다 (docs/04 §7).
create table prompt_risk_snapshots (
    snapshot_id       bigint generated by default as identity,
    input_ref         varchar(64)  not null,
    input_hash        varchar(128) not null,
    evaluation_status varchar(32)  not null check (evaluation_status in ('EVALUATED', 'NOT_EVALUATED')),
    detected          boolean      not null,
    prompt_risk       numeric(5, 4) not null,
    attack_type       varchar(64) check (attack_type in ('IGNORE_PREVIOUS_INSTRUCTION', 'POLICY_BYPASS', 'SYSTEM_PROMPT_EXTRACTION', 'CROSS_CUSTOMER_ACCESS', 'UNAUTHORIZED_TOOL_REQUEST', 'UNKNOWN_PROMPT_ATTACK')),
    model_version     varchar(64)  not null,
    evaluated_at      timestamp(6) with time zone not null,
    primary key (snapshot_id),
    constraint uk_prompt_risk_input_hash_model unique (input_hash, model_version),
    constraint fk_prompt_risk_input foreign key (input_ref) references secured_agent_inputs
);

create table prompt_risk_matched_rules (
    snapshot_id bigint       not null,
    rule_id     varchar(128) not null,
    primary key (snapshot_id, rule_id),
    constraint fk_matched_rules_snapshot foreign key (snapshot_id) references prompt_risk_snapshots
);

-- ---------------------------------------------------------------- 감사
--
-- 아래 두 표에는 FK를 걸지 않는다. 감사 기록은 증거이므로 참조 무결성 위반 때문에
-- 기록 자체가 실패하는 상황을 만들지 않는다.

-- request_id UNIQUE 가 멱등성의 근거다 (docs/04 §17). INSERT 승자만 downstream을 호출한다.
-- 이 제약이 빠지면 중복 금융 호출이 가능해지고, 중복 행이 쌓인 뒤에는 다시 걸 수도 없다.
create table audit_events (
    audit_event_id     varchar(64) not null,
    request_id         varchar(64) not null,
    trace_id           varchar(128),
    agent_id           varchar(64) not null,
    agent_run_id       varchar(64) not null,
    case_id            varchar(64),
    target_consumer_id varchar(64),
    requested_tool     varchar(64) check (requested_tool in ('CREDIT_SCORE_READ', 'INCOME_READ', 'DEBT_READ')),
    prompt_risk        numeric(5, 4),
    behavior_risk      numeric(5, 4),
    decision           varchar(16) check (decision in ('ALLOW', 'BLOCK')),
    downstream_reached boolean,
    response_released  boolean,
    success            boolean,
    records_read       integer,
    latency_ms         bigint,
    policy_version     varchar(64),
    status             varchar(32) not null check (status in ('PROCESSING', 'COMPLETED', 'ERROR')),
    requested_at       timestamp(6) with time zone not null,
    completed_at       timestamp(6) with time zone,
    primary key (audit_event_id),
    constraint uk_audit_event_request_id unique (request_id)
);

create table audit_event_reason_codes (
    audit_event_id varchar(64) not null,
    reason_code    varchar(64) not null,
    primary key (audit_event_id, reason_code),
    constraint fk_reason_codes_audit_event foreign key (audit_event_id) references audit_events
);

-- request_id 에 UNIQUE 를 걸지 않는다. 같은 요청으로 인증이 여러 번 실패하는 것은 정상이고,
-- 그 반복 자체가 관측해야 할 신호다.
create table security_auth_events (
    security_event_id  varchar(64)  not null,
    request_id         varchar(64)  not null,
    trace_id           varchar(128),
    event_type         varchar(32)  not null check (event_type in ('AUTH_FAILURE', 'RATE_LIMITED')),
    reason_code        varchar(64)  not null,
    credential_type    varchar(64)  not null,
    source_fingerprint varchar(128),
    occurred_at        timestamp(6) with time zone not null,
    primary key (security_event_id)
);

-- ---------------------------------------------------------------- 조회 경로 인덱스

-- Behavior History: 특정 Agent의 최근 window 내 완료 이벤트 (docs/04 §9).
create index idx_audit_events_agent_requested_at on audit_events (agent_id, requested_at desc);

-- Dashboard 기본 정렬은 requested_at DESC 다 (docs/06 §25).
create index idx_audit_events_requested_at on audit_events (requested_at desc);

create index idx_security_auth_events_occurred_at on security_auth_events (occurred_at desc);
